
server:
  port: 9000
spring:
  application:
    name: api-gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      globalcors:
        globalcors:
          add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: serve-service
          uri: http://localhost:8086
          predicates:
            - Path=/ws-serve/**
        - id: backoffice-service
          uri: http://localhost:8085
          predicates:
            - Path=/ws-backoffice/**
        - id: emission-service
          uri: http://localhost:8082
          predicates:
            - Path=/ws-emission/**
